main:
    -
        link: /ziekteverzuim/info
        label: Ziekteverzuim
        submenu:
            -
                label: Preventie
                link: /ziekteverzuim/preventie
            -
                label: Coaching
                link: /ziekteverzuim/coaching
            -
                link: /ziekteverzuim/advies
                label: Advies
            -
                link: /ziekteverzuim/ondersteuning
                label: Ondersteuning
    -
        label: Bemiddeling
        link: /bemiddeling/info
        submenu:
            -
                label: 'Voor wie?'
                link: /bemiddeling/voor-wie
            -
                label: 'Waar?'
                link: /bemiddeling/waar
            -
                label: 'Waarvoor?'
                link: /bemiddeling/waarvoor
