main:
    -
        link: /ziekteverzuim/info
        label: Ziekteverzuim
        submenu:
            -
                label: Preventie
                link: /ziekteverzuim/preventie
            -
                label: Coaching
                link: /ziekteverzuim/coaching
            -
                link: /ziekteverzuim/advies
                label: Advies
            -
                link: /ziekteverzuim/ondersteuning
                label: Ondersteuning
            -
                link: /ziekteverzuim/ontzorgen
                label: Ontzorgen
    -
        label: Bemiddeling
        link: /bemiddeling/info
